apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8shealthyimages
spec:
  crd:
    spec:
      names:
        kind: K8sHealthyImages
      validation:
        # Schema for the `parameters` field
        openAPIV3Schema:
          properties:
            repos:
              type: array
              items:
                type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8shealthyimages

        violation[{"msg": msg}] {
          container := input_containers[_]
          satisfied := [good | repo = input.parameters.repos[_] ; good = startswith(container.image, repo)]
          not any(satisfied)
          msg := sprintf("container <%v> has an invalid image repo <%v>, allowed repos are %v", [container.name, container.image, input.parameters.repos])
        }

        violation[{"msg": msg}] {
          container := input_containers[_]
          satisfied := [good | repo = input.parameters.repos[_] ; good = startswith(container.image, repo)]
          all(satisfied)
          repo := input.parameters.repos[_]
          image := get_image(container.image, repo)
          url := sprintf("http://10.0.186.86:8090/process?registry=%v&image=%v", [repo, image])
          response := http.send({"method": "get", "url": url})
          
          response.status_code == 200
          count(response.body) > 0
          msg := sprintf("Detected %v vulnerabilities for image %v, impact: %v", [count(response.body), image, response.body[0].impact])
        }

        get_image(i, repo) = out {
          r := sprintf("%v/", [repo])
          out = replace(i, r, "")
        }

        input_containers[c] {
            c := input.review.object.spec.containers[_]
        }
        input_containers[c] {
            c := input.review.object.spec.initContainers[_]
        }
